service: pdb-slack-bot

provider:
  name: aws
  runtime: ruby2.5

functions:
  invoke:
    handler: handler.invoke
    events:
      - http:
          path: /
          method: post
          cors: true
