service: pdb-slack-bot

provider:
  name: aws
  runtime: ruby2.5

functions:
  command:
    handler: handler.command
    events:
      - http:
          path: /
          method: post
          cors: true
    environment:
      PUPPET_DEBUGGER_URL: https://kamb3pjud7.execute-api.us-east-1.amazonaws.com/dev/eval
